name: Generate index.html from index.md

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python generate_index_html.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        if [ -n "$(git status --porcelain)" ]; then
          git add index.html
          git commit -m "Auto-update index.html from index.md"
          # Wait for initial Pages deployment to start
          sleep 30
          git push
        else
          echo "No changes to commit"
        fi
