name: Generate index.html from index.md

on:
  push:
    branches: [ main ]  # Adjust this if your default branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate index.html
      run: python generate_index_html.py
    
    - name: Setup Pages
      uses: actions/configure-pages@v2
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'  # Upload the entire repository content

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
